#!/usr/bin/env bash

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 243438-web-01:80 check
    server 243438-web-02:80 check
EOF

# Ensure HAProxy can be managed via init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the configuration
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy
