#!/usr/bin/env bash
server {
    listen 80;
    listen [::]:80 default_server;
    server_name 54.210.108.157;
    add_header X-Served-By 243438-web-01;
    
    location /airbnb-onepage {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
