#!/usr/bin/env bash
server {
    listen 80;
    listen [::]:80 default_server;
    server_name 54.210.108.157;
    add_header X-Served-By 243438-web-01;
    
    location /airbnb-onepage {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ~ /airbnb-dynamic/number_odd_or_even/(\d+)$ {
        proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api {
	nclude proxy_params;
        proxy_pass http://127.0.0.1:5002/api;
    }

    location / {
        include proxy_params;
        proxy_pass http://127.0.0.1:5003/2-hbnb/;
    }

    location /static {
        autoindex off;
        alias /home/ubuntu/AirBnB_clone_v4/web_dynamic/static;
    }
}
